# More details can be found here https://github.com/marketplace/actions/auto-request-review

reviewers:
  defaults:
    - team:team-dream # GitHub team

files:
  '.github/**':
    - team:team-devops
  '**':
    - team:team-dream

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 1

  # If it's true, the last matching files-change pattern takes the most precedence (CODEOWNERS-compatible)
  # See https://github.com/necojackarc/auto-request-review/pull/80 for more details.
  last_files_match_only: false
